config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "consultation_requests/index"
  end
  resources :sliders
  get "consultation_requests/new"
  get "consultation_requests/create"
  # Set the admin index as the root path
  #root 'admin#index'
  # config/routes.rb
  resources :reviews, only: [ :new, :create, :destroy]
  get 'reviews', to: 'home#reviews' 
  get 'dashboard', to: 'admin#index'
  get 'about', to: 'home#about'
  get 'ourwork', to: 'home#ourwork'
  post 'ourwork', to: 'home#create_gallery'
  get 'projects', to: 'home#projects'
  get 'tiles-calculator', to: 'home#tiles'
  get 'hardcore-calculator', to: 'home#hardcore'
  get 'concrete-calculator', to: 'home#concrete'
  get 'bricks-calculator', to: 'home#bricks'
  get 'paint-calculator', to: 'home#paint'
  get 'loft-insulation-calculator', to: 'home#loft'
  get 'services', to: 'home#services'

  get 'faq', to: 'home#faq'
  get 'service-details', to: 'home#servicedetails'
  get 'careers', to: 'home#careers'
  get 'appointment', to: 'home#appointment'
  get 'contact', to: 'home#contact'
  root 'home#home'
  post '/', to: 'home#create'
  resources :newsletters, only: [:create]
  resources :consultation_requests, only: [:new, :create] 
  namespace :admin do
    resources :consultation_requests, only: [:index] # Add other actions as needed
  end
  # config/routes.rb
  namespace :admin do
    resources :faqs, except: [:show]
  end

  resources :faqs, only: [:index]


namespace :admin do
  resources :subscriptions
end

  # config/routes.rb
devise_for :admins

  namespace :admin do
    resources :projects
    resources :clients
    resources :feedbacks
  end
  
end

app/models/client.rb
class Client < ApplicationRecord
    has_one_attached :image
    has_many :feedbacks
  end
  

app/controllers/admin/clients_controller.rb
# app/controllers/admin/clients_controller.rb
class Admin::ClientsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @clients = Client.all  # Fetch all clients from the database
  end

  def new
    @client = Client.new  # Initialize a new client instance
  end
  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to admin_clients_path, notice: 'Client was successfully created.'
    else
      render :new
    end
  end
  
  def show
    @client = Client.find(params[:id])  # Find the client by ID
  end
  
  def edit
    @client = Client.find(params[:id])  # Find the client by ID for editing
  end
  
  def update
    @client = Client.find(params[:id])  # Find the client to update
    if @client.update(client_params)
      redirect_to admin_clients_path, notice: 'Client was successfully updated.'  # Redirect to index on success
    else
      render :edit  # Render the edit form again if update fails
    end
  end
  
  def destroy
    @client = Client.find(params[:id])  # Find the client to destroy
    @client.destroy  # Destroy the client
    redirect_to admin_clients_path, notice: 'Client was successfully destroyed.'  # Redirect to index on success
  end
  

  private

  def client_params
    params.require(:client).permit(:name, :company, :image)  # Permit the necessary parameters
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/admin/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <p>
    <strong>Name:</strong>
    <%= client.name %>
  </p>

  <p>
    <strong>Company:</strong>
    <%= client.company %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= client.image %>
  </p>

</div>

app/views/admin/clients/_form.html.erb
<%= form_with(model: @client, url: admin_clients_path, local: true, html: { multipart: true, class: "bg-dark p-4 rounded shadow" }) do |form| %>
  
  <% if @client.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>
      <ul>
        <% @client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label text-light" %>
    <%= form.text_field :name, class: "form-control bg-dark text-light border-light" %>
  </div>

  <div class="mb-3">
    <%= form.label :company, class: "form-label text-light" %>
    <%= form.text_field :company, class: "form-control bg-dark text-light border-light" %>
  </div>

  <div class="mb-3">
    <%= form.label :image, class: "form-label text-light" %>
    <%= form.file_field :image, class: "form-control bg-dark text-light border-light" %>
  </div>

  <div class="actions">
    <%= form.submit "Save Client", class: "btn btn-success btn-lg w-100" %>
  </div>

<% end %>

app/views/admin/clients/edit.html.erb
<% content_for :title, "Editing Client" %>

<h1>Editing Client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Show this Client", admin_client_path(@client) %> |
  <%= link_to "Back to Clients", admin_clients_path %>
</div>

app/views/admin/clients/index.html.erb
<h1 class="mb-4">Clients</h1>

<%= link_to 'New Client', new_admin_client_path, class: 'btn btn-primary mb-3' %>

<div class="table-responsive">
  <table class="table table-striped table-bordered">
    <thead class="table-dark">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Company</th>
        <th scope="col">Image</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @clients.each do |client| %>
        <tr>
          <td><%= client.name %></td>
          <td><%= client.company %></td>
          <td><%= image_tag(client.image, class: 'img-thumbnail', size: '100x100') if client.image.present? %></td>
          <td>
            <%= link_to 'Show', admin_client_path(client), class: 'btn btn-info btn-sm' %>
            <%= link_to 'Edit', edit_admin_client_path(client), class: 'btn btn-warning btn-sm' %>
            <%= button_to 'Destroy', admin_client_path(client), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', admin_clients_path %>

app/views/admin/clients/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @client.company %>
</p>

<p>
  <strong>Image:</strong>
  <% if @client.image.attached? %>
    <%= image_tag @client.image %>
  <% else %>
    No image uploaded
  <% end %>
</p>